---
vms:
  - name: "master01.puppetlabs.demo"
    box:  "puppetlabs/centos-6.5-64-nocm"
    roles: [ "pe-puppet-master" ]

  - name: "master02.puppetlabs.demo"
    box:  "puppetlabs/centos-6.5-64-nocm"
    roles: [ "pe-puppet-master" ]

  - name: "agent01.puppetlabs.demo"
    box: "puppetlabs/centos-6.5-64-nocm"
    roles: [ "pe-puppet-master" ]

  - name: "agent02.puppetlabs.demo"
    box: "puppetlabs/ubuntu-14.04-64-nocm"
    roles: [ "pe-puppet-master" ]
